### ISSUE TITLE
Only Logic Modules should have a ControlSystem association

### ISSUE THREAD

**Issue by caspiano** [PlaceOS/backoffice#122]
Currently, when a module is created via the control system "Add New" flow, the current `control_system_id` is set as the new module's `control_system_id`. 

PlaceOS/models/pull/54 adds validation to ensure only `Logic` Modules are associated directly with a ControlSystem

**Comment by MrYuion** [comment]
Should be fixed in the next build.

**Comment by caspiano** [comment]
@MrYuion could you hold off on closing this issue until it's tested and confirmed to be resolved

**Comment by MrYuion** [comment]
Yeah, let me know if there are any issues.

**Comment by MrYuion** [comment]
@stakach, how should I be working this?

**Comment by stakach** [comment]
So I think @caspiano made a change to disable the use case that @w-le is using here.
However before that change it was meant to work like:

## Logic Drivers

* Must be associated with a `control_system_id`
* Cannot exist in more than one system (*should not* show up in the `Add existing` drop down)

## Device and Service Drivers

* by default should not have `control_system_id` set (important, super annoying if this gets set when you didn't mean for it)
* Can exist in more than one system (*should* show up in the `Add existing` drop down)

however if you wanted a device driver to also have the abilities of a logic driver then you could:

* set `control_system_id` and have this device driver associated with the control system
* Cannot exist in more than one system (*should not* show up in the `Add existing` drop down)

**Comment by w-le** [comment]
based on our external chat, issue can be closed.
We will rewrite the problematic driver as a Logic driver instead of a Service driver. This will require writing two new generic Service drivers to handle placeos and staff api requests

course of action is:
- no further backoffice changes
- no further backend changes
- new generic, public, highly flexible service drivers: placeos api, staff api (these modules should be added to each system that will use them)
- overhaul of visitorMailer and any other Service drivers to change them to Logic drivers
