### ISSUE TITLE
add conference_type field to tenant forms

### ISSUE THREAD

**Issue by stakach** [PlaceOS/backoffice#233]
https://github.com/PlaceOS/staff-api/pull/119/files

**Comment by w-le** [comment]
When the user leaves the Conference Type field blank, please do the POST without the `conference_type` param (instead of with `conference_type: ""` which currently causes backend errors on event create)
<img width="228" alt="Screen Shot 2022-07-21 at 4 45 17 pm" src="https://user-images.githubusercontent.com/10395560/180332848-30e68b82-7ac7-40fc-adee-921a8976b3e6.png">

**Comment by MrYuion** [comment]
@w-le made a change for this.
