### ISSUE TITLE
Bug: Cannot edit the commit of a repository

### ISSUE THREAD

**Issue by caspiano** [PlaceOS/backoffice#79]
![issue](https://user-images.githubusercontent.com/18466497/85499973-f3e2e580-b625-11ea-85bc-a137ed864461.gif)

 - Build: bb5b437 | Built: 23 Jun 2020, 6:07PM
 - Browser: Chrome

**Comment by alexchuvand** [comment]
Ok that is fixed with 2b3e02186bdec2ce7a4572d9b9c3af111f7a3551. 
Getting this error when retrieving commits now.

> ERROR: Hostname lookup for frontends failed: No address found (Socket::Addrinfo::Error)
  from usr/share/crystal/src/socket/addrinfo.cr:125:12 in 'initialize'
  from usr/share/crystal/src/socket/tcp_socket.cr:27:3 in 'new'
  from usr/share/crystal/src/http/client.cr:762:5 in 'socket'
  from usr/share/crystal/src/http/client.cr:650:5 in 'send_request'
  from usr/share/crystal/src/http/client.cr:587:5 in 'exec_internal_single'
  from usr/share/crystal/src/http/client.cr:574:5 in 'exec_internal'
  from usr/share/crystal/src/http/client.cr:570:5 in 'exec'
  from usr/share/crystal/src/http/client.cr:692:5 in 'exec'

**Comment by alexchuvand** [comment]
Ignore the error above. Working fine on the partner env.
